//! Markdown tables for an action or a reusable workflow.
//!
//! The column layouts and placeholders match actdocs, so a document generated
//! by either tool can be regenerated by the other without churn.

use crate::model::{
    ActionInput, ActionSpec, Output, Permission, Secret, WorkflowInput, WorkflowSpec,
};
use crate::parse::Document;
use crate::scalar::escape_pipes;

const DESCRIPTION_TITLE: &str = "## Description";

const INPUTS_TITLE: &str = "## Inputs";
const ACTION_INPUTS_HEADER: &str = "| Name | Description | Default | Required |";
const ACTION_INPUTS_ALIGNMENT: &str = "| :--- | :---------- | :------ | :------: |";
const WORKFLOW_INPUTS_HEADER: &str = "| Name | Description | Type | Default | Required |";
const WORKFLOW_INPUTS_ALIGNMENT: &str = "| :--- | :---------- | :--- | :------ | :------: |";

const SECRETS_TITLE: &str = "## Secrets";
const SECRETS_HEADER: &str = "| Name | Description | Required |";
const SECRETS_ALIGNMENT: &str = "| :--- | :---------- | :------: |";

const OUTPUTS_TITLE: &str = "## Outputs";
const OUTPUTS_HEADER: &str = "| Name | Description |";
const OUTPUTS_ALIGNMENT: &str = "| :--- | :---------- |";

const PERMISSIONS_TITLE: &str = "## Permissions";
const PERMISSIONS_HEADER: &str = "| Scope | Access |";
const PERMISSIONS_ALIGNMENT: &str = "| :--- | :---- |";

/// Body of a section that exists but has no entries.
const EMPTY_SECTION: &str = "N/A";

/// Render whichever kind of document this is.
pub fn document(document: &Document, omit: bool) -> String {
    match document {
        Document::Action(spec) => action(spec, omit),
        Document::Workflow(spec) => workflow(spec, omit),
    }
}

pub fn action(spec: &ActionSpec, omit: bool) -> String {
    join([
        description(spec, omit),
        table(
            INPUTS_TITLE,
            ACTION_INPUTS_HEADER,
            ACTION_INPUTS_ALIGNMENT,
            &rows(&spec.inputs, action_input_row),
            omit,
        ),
        table(
            OUTPUTS_TITLE,
            OUTPUTS_HEADER,
            OUTPUTS_ALIGNMENT,
            &rows(&spec.outputs, output_row),
            omit,
        ),
    ])
}

pub fn workflow(spec: &WorkflowSpec, omit: bool) -> String {
    join([
        table(
            INPUTS_TITLE,
            WORKFLOW_INPUTS_HEADER,
            WORKFLOW_INPUTS_ALIGNMENT,
            &rows(&spec.inputs, workflow_input_row),
            omit,
        ),
        table(
            SECRETS_TITLE,
            SECRETS_HEADER,
            SECRETS_ALIGNMENT,
            &rows(&spec.secrets, secret_row),
            omit,
        ),
        table(
            OUTPUTS_TITLE,
            OUTPUTS_HEADER,
            OUTPUTS_ALIGNMENT,
            &rows(&spec.outputs, output_row),
            omit,
        ),
        table(
            PERMISSIONS_TITLE,
            PERMISSIONS_HEADER,
            PERMISSIONS_ALIGNMENT,
            &rows(&spec.permissions, permission_row),
            omit,
        ),
    ])
}

/// Separate the sections that survived by exactly one blank line.
///
/// Dropping the empty ones before joining is what keeps `--omit` from leaving a
/// run of blank lines where a section used to be.
fn join(sections: impl IntoIterator<Item = Option<String>>) -> String {
    sections
        .into_iter()
        .flatten()
        .collect::<Vec<_>>()
        .join("\n\n")
}

fn description(spec: &ActionSpec, omit: bool) -> Option<String> {
    if omit && !spec.description.is_present() {
        return None;
    }
    Some(format!(
        "{DESCRIPTION_TITLE}\n\n{}",
        spec.description.section_text()
    ))
}

fn table(
    title: &str,
    header: &str,
    alignment: &str,
    rows: &[String],
    omit: bool,
) -> Option<String> {
    if omit && rows.is_empty() {
        return None;
    }

    let mut section = String::from(title);
    section.push_str("\n\n");

    if rows.is_empty() {
        section.push_str(EMPTY_SECTION);
    } else {
        section.push_str(header);
        section.push('\n');
        section.push_str(alignment);
        for row in rows {
            section.push('\n');
            section.push_str(row);
        }
    }

    Some(section)
}

fn rows<T>(entries: &[T], row: impl Fn(&T) -> String) -> Vec<String> {
    entries.iter().map(row).collect()
}

fn action_input_row(input: &ActionInput) -> String {
    format!(
        "| {} | {} | {} | {} |",
        escape_pipes(&input.name),
        input.description.cell_text(),
        input.default.cell_code(),
        input.required.cell_flag()
    )
}

fn workflow_input_row(input: &WorkflowInput) -> String {
    format!(
        "| {} | {} | {} | {} | {} |",
        escape_pipes(&input.name),
        input.description.cell_text(),
        input.r#type.cell_code(),
        input.default.cell_code(),
        input.required.cell_flag()
    )
}

fn secret_row(secret: &Secret) -> String {
    format!(
        "| {} | {} | {} |",
        escape_pipes(&secret.name),
        secret.description.cell_text(),
        secret.required.cell_flag()
    )
}

fn output_row(output: &Output) -> String {
    format!(
        "| {} | {} |",
        escape_pipes(&output.name),
        output.description.cell_text()
    )
}

fn permission_row(permission: &Permission) -> String {
    format!(
        "| {} | {} |",
        escape_pipes(&permission.scope),
        escape_pipes(&permission.access)
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scalar::Scalar;

    #[test]
    fn an_empty_action_still_shows_every_section() {
        assert_eq!(
            action(&ActionSpec::default(), false),
            "## Description\n\nN/A\n\n## Inputs\n\nN/A\n\n## Outputs\n\nN/A"
        );
    }

    #[test]
    fn omit_removes_an_empty_action_entirely() {
        assert_eq!(action(&ActionSpec::default(), true), "");
    }

    #[test]
    fn omit_leaves_one_blank_line_where_a_section_was() {
        let spec = WorkflowSpec {
            inputs: vec![WorkflowInput {
                name: "flag".to_owned(),
                description: Scalar::null(),
                default: Scalar::null(),
                required: Scalar::null(),
                r#type: Scalar::new("boolean"),
            }],
            permissions: vec![Permission {
                scope: "contents".to_owned(),
                access: "read".to_owned(),
            }],
            ..WorkflowSpec::default()
        };

        // Secrets and outputs sit between the two surviving sections.
        assert_eq!(
            workflow(&spec, true),
            "## Inputs\n\n\
             | Name | Description | Type | Default | Required |\n\
             | :--- | :---------- | :--- | :------ | :------: |\n\
             | flag |  | `boolean` | n/a | no |\n\
             \n\
             ## Permissions\n\n\
             | Scope | Access |\n\
             | :--- | :---- |\n\
             | contents | read |"
        );
    }

    #[test]
    fn a_pipe_in_a_name_cannot_break_the_table() {
        let spec = ActionSpec {
            outputs: vec![Output {
                name: "a|b".to_owned(),
                description: Scalar::new("c|d"),
            }],
            ..ActionSpec::default()
        };

        assert!(
            action(&spec, true).ends_with("| a\\|b | c\\|d |"),
            "got {}",
            action(&spec, true)
        );
    }

    #[test]
    fn nothing_rendered_ends_with_whitespace() {
        let rendered = action(&ActionSpec::default(), false);
        assert_eq!(rendered.trim_end(), rendered);
    }
}
